version: '3.8'
services:
  postgres:
    image: postgres:10-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
volumes:
  db:
    driver: local